USE customer_behaviour

select TOP 10 * from customer_shopping_behaviour_cleaned

--1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount_usd) as revenue
from customer_shopping_behaviour_cleaned
group by gender

--2. Which customers used a discount but still spend more than the average purchase amount?
select customer_id, purchase_amount_usd from customer_shopping_behaviour_cleaned
where discount_applied = 'Yes' and purchase_amount_usd>= (select AVG(purchase_amount_usd) from customer_shopping_behaviour_cleaned)

--3. Which are the top 5 products with highest average review rating?
select TOP 5 item_purchased, ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) as "Average Product Rating" from customer_shopping_behaviour_cleaned
group by item_purchased
order by avg(cast(review_rating as decimal(10,2))) desc

--4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(cast(purchase_amount_usd as decimal(10,2))),2) from customer_shopping_behaviour_cleaned
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers.
select subscription_status, count(customer_id) as total_customers, round(AVG(cast(purchase_amount_usd as decimal (10,2))),2) as avg_spend, round(sum(cast(purchase_amount_usd as decimal(10,2))),2) as total_revenue
from customer_shopping_behaviour_cleaned
group by subscription_status
order by total_revenue, avg_spend desc;

--6. Which products have the highest percentage of purchases with discount applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_rate
FROM customer_shopping_behaviour_cleaned
GROUP BY item_purchased
order by discount_rate desc;


--7. Segment customers into New, Returning and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases =1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segmentation
from customer_shopping_behaviour_cleaned
)

select customer_segmentation, count(*) as "Number of Customers" from customer_type
group by customer_segmentation 

--8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behaviour_cleaned
group by category, item_purchased
)


select item_rank, category, item_purchased, total_orders from item_counts
where item_rank <=3

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer_shopping_behaviour_cleaned
where previous_purchases>5
group by subscription_status

--10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount_usd) as total_revenue from customer_shopping_behaviour_cleaned
group by age_group
order by total_revenue desc;